Write-Output ""
Write-Output "CineCritic API -> http://localhost:5000"
Write-Output "Route map:"
Write-Output "POST   /api/v1/user/signup"
Write-Output "POST   /api/v1/user/signin"
Write-Output "PUT    /api/v1/user/update-password"
Write-Output "GET    /api/v1/user/info"
Write-Output "GET    /api/v1/user/favorites"
Write-Output "POST   /api/v1/user/favorites"
Write-Output "DELETE /api/v1/user/favorites/:favoriteId"
Write-Output "GET    /api/v1/reviews"
Write-Output "POST   /api/v1/reviews"
Write-Output "DELETE /api/v1/reviews/:reviewId"
Write-Output "GET    /api/v1/person/:personId"
Write-Output "GET    /api/v1/person/:personId/medias"
Write-Output "GET    /api/v1/:mediaType/search"
Write-Output "GET    /api/v1/:mediaType/genres"
Write-Output "GET    /api/v1/:mediaType/detail/:mediaId"
Write-Output "GET    /api/v1/:mediaType/:mediaCategory"
Write-Output ""
Write-Output "Quick test lines:"
Write-Output "GET    /api/v1/movie/popular"
Write-Output "GET    /api/v1/movie/detail/550"
Write-Output "GET    /api/v1/tv/top_rated"
Write-Output "GET    /api/v1/people/search?query=tom&page=1"
Write-Output "POST   /api/v1/user/signin"
Write-Output ""
Write-Output "Protected routes require header: Authorization: Bearer <token>"
Write-Output ""